# Generated by Django 5.1.2 on 2025-10-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_referral_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfcmtoken',
            name='subscription',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfcmtoken',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
