# Generated by Django 5.1.2 on 2026-04-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFCMToken',
        ),
    ]
