# Generated by Django 5.1.2 on 2026-05-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_pushsubscription_user_delete_userfcmtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
