# Generated by Django 5.1.2 on 2026-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_pushsubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('user', 'endpoint')},
        ),
    ]
