# Generated by Django 5.1.2 on 2026-05-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cartitem_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
