# Generated by Django 5.1.2 on 2026-05-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_cartitem_product_remove_order_product'),
        ('product', '0018_remove_product_datesold_remove_product_extra_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productCartItems', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.productvariant'),
        ),
    ]
