# Generated by Django 5.1.2 on 2026-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('imagefile', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image', models.URLField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('datesold', models.DateTimeField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('is_sticky', models.BooleanField(default=False)),
                ('sticky_timestamp', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='category_products', to='product.category')),
            ],
        ),
    ]
