# Generated by Django 5.1.2 on 2026-05-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('request', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='request',
        ),
        migrations.AddField(
            model_name='product',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_product', to='request.request'),
        ),
    ]
