# Generated by Django 5.1.2 on 2026-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productvariant_request_product_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
