# Generated by Django 5.1.2 on 2026-05-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_category_icon'),
        ('request', '0003_remove_request_buyer_call_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datesold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagefile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='negotiable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='request',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='used',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('imagefile', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image', models.URLField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('datesold', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_variants', to='request.request')),
            ],
            options={
                'unique_together': {('product', 'sku')},
            },
        ),
    ]
