# Generated by Django 5.1.2 on 2025-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagefile',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products_images/'),
        ),
    ]
