# Generated by Django 5.1.2 on 2026-05-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_product_datesold_remove_product_extra_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_products', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
