# Generated by Django 5.1.2 on 2026-05-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_preferred_variant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
